### ISSUE TITLE
HTTP2 not detected

### ISSUE THREAD

**Issue by oviliz** [magehost/performance-dashboard#5]
I'm getting "Your connection is HTTP 1.0" while any online tool tells I'm on HTTP/2 and knowing the server configuration is also a confirmation.

Is there anything I can help to debug the plugin detection?
Magento 2.2.2 / PHP 7.1.13 / NGINX 1.13.6 (HTTP/2) in front of Apache 2.4.28 (https://serverpilot.io/community/articles/how-serverpilot-configures-your-lamp-stack.html)

**Comment by jeroenvermeulen** [comment]
Can you put a `<?php phpinfo()` on the server and post the contents of `$_SERVER` here? You can anonymise sensitive stuff like IP's and domains.

**Comment by oviliz** [comment]
It shows indeed HTTP/1.0. I've got back to ServerPilot to learn of their explanation. I shall update here, thanks.

**Comment by oviliz** [comment]
ServerPilot replied saying that phpinfo output won't show whether HTTP/2 is used between the client and Nginx, which is where you'd want to verify (e.g. https://serverpilot.io/community/articles/how-to-confirm-http2-works-on-your-site.html).

**Comment by jeroenvermeulen** [comment]
- Does your developer tools or [chrome://net-internals/#http2](chrome://net-internals/#http2) list your connection as HTTP/2 ?
- I wonder why PHP would say "HTTP/1.0" then on your server. If it would show nothing it would be easier to believe PHP doen't know the answer.
- The extension of course runs in PHP, do you have a sugestion how to tell if HTTP/2 is active?

**Comment by oviliz** [comment]
Yes, it does (this is the website, https://shop.timefortruth.co.uk). I have no idea, to be honest.

**Comment by jeroenvermeulen** [comment]
The front of your shop, Nginx is indeed running HTTP/2.
The Apache in between is HTTP/1, that is what PHP shows.
So in fact your setup is not truly HTTP/2. 
It is almost impossible to detect this setup from PHP, and give the right advise in our extension.
Maybe JavaScript detection of HTTP/2 is possible, but still your setup is not truly HTTP/2, so I don't know what the Performance Dashboard should indicate or advise.

**Comment by jeroenvermeulen** [comment]
Closing this issue, one month without feedback and no direction for a solution.
